In [10]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(5.0)

x*y*x 

tensor(45.)

In [11]:
q = torch.arange(10)

len(q),q

(10, tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

torch.arange(N) 自动从零开始生成向量到N
len（）

In [12]:
w = torch.arange(20).reshape(5, 4)

w, w.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [22]:
import random


# 声明方法 
# 方法作用：生成随机数0，1 并将其加入到初始列表之中
def appendlist():
    listw = []
    for q in range(9):
        e = random.randint(0, 1)
        listw.append(e)
    qqqq = torch.tensor(listw).reshape(3, 3)
    print(qqqq)
    print('********************************')
    return listw

# 使用方法
qwe = appendlist()
asd = appendlist()
zxc = appendlist()

# 将以上的三个列表进行组合 组合为一个列表中嵌套三个小列表
qqq = [qwe, asd, zxc]

# 将列表转换为矩阵（三维）
www = torch.tensor(qqq).reshape(3, 3, 3)
print('以下为由三个二维向量合并为一个三维向量进行转换：\n', www)


tensor([[0, 0, 1],
        [0, 0, 0],
        [1, 1, 0]])
********************************
tensor([[1, 0, 0],
        [0, 1, 0],
        [1, 0, 1]])
********************************
tensor([[0, 1, 1],
        [1, 1, 0],
        [0, 0, 0]])
********************************
以下为由三个二维向量合并为一个三维向量进行转换：
 tensor([[[0, 0, 1],
         [0, 0, 0],
         [1, 1, 0]],

        [[1, 0, 0],
         [0, 1, 0],
         [1, 0, 1]],

        [[0, 1, 1],
         [1, 1, 0],
         [0, 0, 0]]])


In [21]:
X = torch.arange(27).reshape(3, 3, 3) # reshape（组， 列， 行）
X

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])